# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Town',
        ),
    ]
