# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 05:16
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_town_in_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['title'], 'verbose_name': '\u0413\u043e\u0440\u043e\u0434', 'verbose_name_plural': '         \u0413\u043e\u0440\u043e\u0434\u0430'},
        ),
        migrations.AddField(
            model_name='town',
            name='description_instructor',
            field=tinymce.models.HTMLField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442\u043e\u0432\u044b\u0439 \u0431\u043b\u043e\u043a \u0438\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440\u0430'),
        ),
    ]
