# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_town_meta_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='meta_description',
        ),
    ]
