# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
