# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_auto_20170529_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('inn', models.CharField(max_length=12, verbose_name='\u0418\u041d\u041d')),
                ('kpp', models.CharField(max_length=100, verbose_name='\u041a\u041f\u041f')),
                ('bik', models.CharField(blank=True, max_length=12, verbose_name='\u0411\u0418\u041a')),
                ('bank', models.CharField(max_length=100, verbose_name='\u0411\u0430\u043d\u043a')),
                ('raschet_bill', models.CharField(max_length=25, verbose_name='\u0420\u0430\u0441\u0447\u0435\u0442\u043d\u044b\u0439 \u0441\u0447\u0435\u0442')),
                ('zip_address', models.CharField(max_length=500, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0430\u0434\u0440\u0435\u0441')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0421\u0447\u0435\u0442',
                'verbose_name_plural': '\u0421\u0447\u0435\u0442\u0430',
            },
        ),
    ]
