# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_social_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.CharField(max_length=300, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
