# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20170807_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_premium_off',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f \u043f\u0440\u0435\u043c\u0438\u0443\u043c'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_premium_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0432\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f \u043f\u0440\u0435\u043c\u0438\u0443\u043c'),
        ),
    ]
