# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20170807_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '\u0418\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440'), ('2', '\u0410\u0432\u0442\u043e\u0448\u043a\u043e\u043b\u0430'), ('3', '\u041e\u0442\u0437\u044b\u0432\u044b')], default=3, max_length=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
    ]
