# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170622_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='sd', unique=True, verbose_name='url'),
        ),
    ]
