# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
