# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20170807_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='name',
            field=models.CharField(max_length=300, verbose_name='\u0418\u043c\u044f'),
        ),
    ]
