# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20170807_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='born',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
    ]
