# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_faq_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='verificy',
            field=models.BooleanField(default=False, verbose_name='\u0412\u0435\u0440\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f \u043f\u0440\u043e\u0439\u0434\u0435\u043d\u0430'),
        ),
    ]
