# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20171103_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-born'], 'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441-\u043e\u0442\u0432\u0435\u0442', 'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b-\u043e\u0442\u0432\u0435\u0442\u044b'},
        ),
    ]
