# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170413_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='born',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 13, 19, 58, 41, 487572, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='new',
            name='born',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 13, 19, 58, 41, 486925, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
    ]
