# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20170417_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='keywords',
        ),
    ]
