# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20170626_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'),
        ),
    ]
