# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20170724_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pict1',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='news',
            name='pict2',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='news',
            name='pict3',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='news',
            name='pict4',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pict',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
