# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodrome',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='autodrome',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='longitude',
        ),
    ]
