# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170410_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='region',
        ),
    ]
