# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 09:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20170411_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name=b'\xd0\xa4.\xd0\x98.\xd0\x9e.')),
                ('age', models.SmallIntegerField(verbose_name=b'\xd0\x92\xd0\xbe\xd0\xb7\xd1\x80\xd0\xb0\xd1\x81\xd1\x82')),
                ('zodiac', models.CharField(max_length=200, verbose_name=b'\xd0\x97\xd0\xbd\xd0\xb0\xd0\xba \xd0\xb7\xd0\xbe\xd0\xb4\xd0\xb8\xd0\xb0\xd0\xba\xd0\xb0')),
                ('experience', models.SmallIntegerField(verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd0\xb6 \xd0\xb2\xd0\xbe\xd0\xb6\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f')),
                ('coast', models.SmallIntegerField(verbose_name=b'\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0 \xd1\x87\xd0\xb0\xd1\x81\xd0\xb0 \xd0\xb2\xd0\xbe\xd0\xb6\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f')),
                ('car', models.CharField(max_length=200, verbose_name=b'\xd0\x9c\xd0\xb0\xd1\x80\xd0\xba\xd0\xb0 \xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe\xd0\xbc\xd0\xbe\xd0\xb1\xd0\xb8\xd0\xbb\xd1\x8f')),
                ('credo', models.CharField(max_length=300, verbose_name=b'\xd0\x96\xd0\xb8\xd0\xb7\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xba\xd1\x80\xd0\xb5\xd0\xb4\xd0\xbe')),
                ('hobby', models.CharField(max_length=300, verbose_name=b'\xd0\xa5\xd0\xbe\xd0\xb1\xd0\xb1\xd0\xb8')),
                ('about_you', models.TextField(verbose_name=b'\xd0\xa0\xd0\xb0\xd1\x81\xd1\x81\xd0\xba\xd0\xb0\xd0\xb6\xd0\xb8\xd1\x82\xd0\xb5 \xd0\xbe \xd1\x81\xd0\xb5\xd0\xb1\xd0\xb5')),
                ('about_teach', models.TextField(verbose_name=b'\xd0\xa0\xd0\xb0\xd1\x81\xd1\x81\xd0\xba\xd0\xb0\xd0\xb6\xd0\xb8\xd1\x82\xd0\xb5 \xd0\xbe \xd1\x81\xd0\xb8\xd1\x81\xd1\x82\xd0\xb5\xd0\xbc\xd0\xb5 \xd0\xbe\xd0\xb1\xd1\x83\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f')),
                ('logo', models.ImageField(upload_to=b'logo', verbose_name=b'\xd0\x9b\xd0\xbe\xd0\xb3\xd0\xbe')),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')], verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd')),
                ('category_education', models.ManyToManyField(blank=True, to='school.Category_education', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f \xd0\xbe\xd0\xb1\xd1\x83\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.City', verbose_name=b'\xd0\x93\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4')),
            ],
            options={
                'verbose_name': '\u0418\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440',
                'verbose_name_plural': '\u0418\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Teachcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
            ],
            options={
                'verbose_name': '\u0410\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044c \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0410\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044c \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='teachcar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teachcar', verbose_name=b'\xd0\x97\xd0\xb0\xd0\xbd\xd1\x8f\xd1\x82\xd0\xb8\xd1\x8f'),
        ),
    ]
