# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 18:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0005_auto_20170411_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446'),
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446'),
        ),
        migrations.AlterField(
            model_name='additionally',
            name='title',
            field=models.CharField(max_length=60, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='autodrome',
            name='adress',
            field=models.CharField(max_length=300, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='autodrome',
            name='description_adress',
            field=models.CharField(max_length=500, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='autodrome',
            name='metro',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u041c\u0435\u0442\u0440\u043e'),
        ),
        migrations.AlterField(
            model_name='autodrome',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='\u0428\u043a\u043e\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='autodrome',
            name='title',
            field=models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='adress',
            field=models.CharField(max_length=300, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='description_adress',
            field=models.CharField(max_length=500, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='metro',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u041c\u0435\u0442\u0440\u043e'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='\u0428\u043a\u043e\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='category_education',
            name='title',
            field=models.CharField(max_length=10, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='about_teach',
            field=models.TextField(verbose_name='\u0420\u0430\u0441\u0441\u043a\u0430\u0436\u0438\u0442\u0435 \u043e \u0441\u0438\u0441\u0442\u0435\u043c\u0435 \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='about_you',
            field=models.TextField(verbose_name='\u0420\u0430\u0441\u0441\u043a\u0430\u0436\u0438\u0442\u0435 \u043e \u0441\u0435\u0431\u0435'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='age',
            field=models.SmallIntegerField(verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='car',
            field=models.CharField(max_length=200, verbose_name='\u041c\u0430\u0440\u043a\u0430 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='category_education',
            field=models.ManyToManyField(blank=True, to='school.Category_education', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='coast',
            field=models.SmallIntegerField(verbose_name='\u0426\u0435\u043d\u0430 \u0447\u0430\u0441\u0430 \u0432\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='credo',
            field=models.CharField(max_length=300, verbose_name='\u0416\u0438\u0437\u043d\u0435\u043d\u043d\u043e\u0435 \u043a\u0440\u0435\u0434\u043e'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='experience',
            field=models.SmallIntegerField(verbose_name='\u0421\u0442\u0430\u0436 \u0432\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='\u0424.\u0418.\u041e.'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='hobby',
            field=models.CharField(max_length=300, verbose_name='\u0425\u043e\u0431\u0431\u0438'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='logo',
            field=models.ImageField(upload_to='logo', verbose_name='\u041b\u043e\u0433\u043e'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='teachcar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teachcar', verbose_name='\u0417\u0430\u043d\u044f\u0442\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='zodiac',
            field=models.CharField(max_length=200, verbose_name='\u0417\u043d\u0430\u043a \u0437\u043e\u0434\u0438\u0430\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='school',
            name='additionally',
            field=models.ManyToManyField(blank=True, to='school.Additionally', verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='school',
            name='adress',
            field=models.CharField(max_length=300, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='school',
            name='category_education',
            field=models.ManyToManyField(blank=True, to='school.Category_education', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='school',
            name='cost',
            field=models.PositiveIntegerField(blank=True, verbose_name='\u0426\u0435\u043d\u0430 \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description_adress',
            field=models.CharField(max_length=500, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(upload_to='logo', verbose_name='\u041b\u043e\u0433\u043e'),
        ),
        migrations.AlterField(
            model_name='school',
            name='metro',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u041c\u0435\u0442\u0440\u043e'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='school',
            name='site',
            field=models.URLField(blank=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0441\u0430\u0439\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='school',
            name='term',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='\u0421\u0440\u043e\u043a \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='teachcar',
            name='title',
            field=models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
