# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20170413_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u0435\u043c\u0438\u0443\u043c'),
        ),
    ]
