# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='born',
            field=models.DateField(default=datetime.datetime(2017, 4, 13, 19, 46, 29, 268846), verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
    ]
