# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20170413_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='born',
            field=models.DateField(default=datetime.datetime(2017, 4, 13, 19, 48, 31, 700547), verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=300, verbose_name='\u0418\u043c\u044f'),
        ),
    ]
