# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20170416_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='body',
            field=models.CharField(default='\u041a\u043b\u044e\u0447\u0438', max_length=1000, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(default='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435', max_length=300),
        ),
    ]
