# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 07:43
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_school_geo'),
    ]

