# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 08:31
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20170416_0824'),
    ]
