# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 08:32
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20170416_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='geo',
        )
 
    ]
