# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 09:38
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_auto_20170416_0832'),
    ]

