# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_city_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='position',
        ),
    ]
