# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_auto_20170416_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default='1', max_length=300, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
    ]
