# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_school_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='address',
            new_name='adress',
        ),
    ]
