# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_auto_20170418_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pict', models.ImageField(max_length=300, upload_to=b'', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={
                'verbose_name': '\u0410\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044c \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f',
            },
        ),
    ]
