# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_schoolimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='category_education',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='teachcar',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='schoolimage',
            options={'verbose_name': '\u0424\u043e\u0442\u043e \u0448\u043a\u043e\u043b\u044b'},
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Teachcar',
        ),
    ]
