# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_auto_20170420_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='additionally',
        ),
        migrations.AddField(
            model_name='school',
            name='med',
            field=models.BooleanField(default=False, verbose_name='\u041c\u0435\u0434\u0438\u0446\u0438\u043d\u0441\u043a\u0430\u044f \u043a\u043d\u0438\u0436\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='school',
            name='photograph',
            field=models.BooleanField(default=False, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444'),
        ),
        migrations.DeleteModel(
            name='Additionally',
        ),
    ]
