# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_auto_20170430_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='term',
            field=models.CharField(blank=True, max_length=4, verbose_name='\u0421\u0440\u043e\u043a \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
    ]
