# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_auto_20170502_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
