# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_auto_20170525_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['premium'], 'verbose_name': '\u0428\u043a\u043e\u043b\u0430', 'verbose_name_plural': '\u0428\u043a\u043e\u043b\u044b'},
        ),
        migrations.AlterField(
            model_name='schoolimage',
            name='pict',
            field=models.ImageField(max_length=300, upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
