# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_auto_20170531_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '\u0428\u043a\u043e\u043b\u0430', 'verbose_name_plural': '\u0428\u043a\u043e\u043b\u044b'},
        ),
    ]
