# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0056_auto_20170531_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verificated',
            field=models.BooleanField(default=False),
        ),
    ]
