# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_review_verificated'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='default@ya.ru', max_length=254),
        ),
    ]
