# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_auto_20170603_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='verificated',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d'),
        ),
    ]
