# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0062_auto_20170801_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_group',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='fc',
            field=models.CharField(blank=True, default='http://vk.com/mygroup', max_length=300, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0432 \u0424\u044d\u0439\u0441\u0431\u0443\u043a'),
        ),
        migrations.AddField(
            model_name='school',
            name='od',
            field=models.CharField(blank=True, default='http://vk.com/mygroup', max_length=300, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0432 \u041e\u0434\u043d\u043e\u043a\u043b\u0430\u0441\u0441\u043d\u0438\u043a\u0430\u0445'),
        ),
        migrations.AddField(
            model_name='school',
            name='tw',
            field=models.CharField(blank=True, default='http://vk.com/mygroup', max_length=300, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0432 \u0422\u0432\u0438\u0442\u0435\u0440\u0435'),
        ),
        migrations.AddField(
            model_name='school',
            name='vk',
            field=models.CharField(blank=True, default='http://vk.com/mygroup', max_length=300, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0432 \u0412\u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0435'),
        ),
        migrations.DeleteModel(
            name='Social_group',
        ),
    ]
