# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0066_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autodrome',
            options={'verbose_name': '\u0410\u0432\u0442\u043e\u0434\u0440\u043e\u043c', 'verbose_name_plural': '   \u0410\u0432\u0442\u043e\u0434\u0440\u043e\u043c\u044b'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '\u0424\u0438\u043b\u0438\u0430\u043b', 'verbose_name_plural': '  \u0424\u0438\u043b\u0438\u0430\u043b\u044b'},
        ),
        migrations.AlterModelOptions(
            name='category_education',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f', 'verbose_name_plural': '      \u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442', 'verbose_name_plural': '       \u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b \u0434\u043b\u044f \u0441\u043a\u0430\u0447\u0438\u0432\u0430\u043d\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '\u041e\u0442\u0437\u044b\u0432', 'verbose_name_plural': '    \u041e\u0442\u0437\u044b\u0432\u044b'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '\u0428\u043a\u043e\u043b\u0430', 'verbose_name_plural': ' \u0428\u043a\u043e\u043b\u044b'},
        ),
        migrations.AlterModelOptions(
            name='schoolimage',
            options={'verbose_name': '     \u0424\u043e\u0442\u043e \u0448\u043a\u043e\u043b\u044b'},
        ),
    ]
