# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0068_auto_20170802_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=school.models.get_upload_path, verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b'),
        ),
    ]
