# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0069_auto_20170802_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('img', models.ImageField(upload_to=school.models.get_upload_path, verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='\u0428\u043a\u043e\u043b\u0430')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442',
                'verbose_name_plural': '        \u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b \u0430\u0432\u0442\u043e\u0448\u043a\u043e\u043b',
            },
        ),
    ]
