# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0071_auto_20170811_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResponce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Review', verbose_name='\u041e\u0442\u0437\u044b\u0432')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u043e\u0442\u0437\u044b\u0432',
                'verbose_name_plural': '         \u041e\u0442\u0432\u0435\u0442\u044b \u043d\u0430 \u043e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
    ]
