# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0073_feedbackscholl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbackscholl',
            new_name='Feedbackschool',
        ),
    ]
