# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0074_auto_20171101_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackschool',
            name='category',
        ),
        migrations.AddField(
            model_name='feedbackschool',
            name='category',
            field=models.ManyToManyField(to='school.Category_education', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
    ]
