# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0077_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackschool',
            name='category',
        ),
    ]
