# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0079_feedbackschool_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackschool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
