# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0080_auto_20171111_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackschool',
            options={'ordering': ['-created_at'], 'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430', 'verbose_name_plural': '                \u0417\u0430\u044f\u0432\u043a\u0438 \u0430\u0432\u0442\u043e\u0448\u043a\u043e\u043b'},
        ),
    ]
