# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20180126_0211'),
        ('school', '0085_school_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='town2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='city.Town'),
        ),
    ]
