# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0087_auto_20180126_0249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
