# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0088_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='text_unique_price',
            field=models.CharField(blank=True, max_length=1000, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043f\u043e\u043b\u044f \u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u043e\u0439 \u0446\u0435\u043d\u044b'),
        ),
    ]
