# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0092_auto_20180218_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_town',
            field=models.ForeignKey(default=122, on_delete=django.db.models.deletion.CASCADE, to='city.Town'),
        ),
    ]
