# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0094_auto_20180614_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(default='\u041c\u043e\u0441\u043a\u0432\u0430', max_length=300, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
