# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['title'], 'verbose_name': '\u0422\u0435\u0441\u0442', 'verbose_name_plural': '\u0422\u0435\u0441\u0442\u044b'},
        ),
    ]
