# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170622_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('offence', tinymce.models.HTMLField(verbose_name='\u041d\u0430\u0440\u0443\u0448\u0435\u043d\u0438\u0435')),
                ('article', models.CharField(max_length=100, verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f')),
                ('sanction', models.CharField(max_length=400, verbose_name='\u0421\u0430\u043d\u043a\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u0428\u0442\u0440\u0430\u0444',
                'verbose_name_plural': '\u0428\u0442\u0440\u0430\u0444\u044b',
            },
        ),
        migrations.CreateModel(
            name='Fine_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0437\u0434\u0435\u043b \u0448\u0442\u0440\u0430\u0444\u0430',
                'verbose_name_plural': '\u0420\u0430\u0437\u0434\u0435\u043b\u044b \u0448\u0442\u0440\u0430\u0444\u0430',
            },
        ),
        migrations.AddField(
            model_name='fine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Fine_category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
