# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170724_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('body', tinymce.models.HTMLField(verbose_name='\u041d\u0430\u0440\u0443\u0448\u0435\u043d\u0438\u0435')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Fine_category', verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0430\u0432\u0438\u043b\u0430',
                'verbose_name_plural': '\u041f\u0440\u0430\u0432\u0438\u043b\u043e',
            },
        ),
        migrations.CreateModel(
            name='Rules_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0437\u0434\u0435\u043b \u0448\u0442\u0440\u0430\u0444\u0430',
                'verbose_name_plural': '\u0420\u0430\u0437\u0434\u0435\u043b\u044b \u0448\u0442\u0440\u0430\u0444\u0430',
            },
        ),
        migrations.AlterField(
            model_name='fine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Fine_category', verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b'),
        ),
    ]
