# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170726_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': '\u041f\u0440\u0430\u0432\u0438\u043b\u043e', 'verbose_name_plural': '\u041f\u0440\u0430\u0432\u0438\u043b\u0430'},
        ),
        migrations.AlterModelOptions(
            name='rules_category',
            options={'verbose_name': '\u0420\u0430\u0437\u0434\u0435\u043b \u043f\u0440\u0430\u0432\u0438\u043b', 'verbose_name_plural': '\u0420\u0430\u0437\u0434\u0435\u043b\u044b \u043f\u0440\u0430\u0432\u0438\u043b'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Rules_category', verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b'),
        ),
    ]
