# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170726_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('body', tinymce.models.HTMLField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0440\u043e\u0436\u043d\u0430\u044f \u0440\u0430\u0437\u043c\u0435\u0442\u043a\u0430',
                'verbose_name_plural': '\u0414\u043e\u0440\u043e\u0436\u043d\u044b\u0435 \u0440\u0430\u0437\u043c\u0435\u0442\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Roadsing_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0437\u0434\u0435\u043b \u0434\u043e\u0440\u043e\u0436\u043d\u044b\u0445 \u0437\u043d\u0430\u043a\u043e\u0432',
                'verbose_name_plural': '\u0420\u0430\u0437\u0434\u0435\u043b\u044b \u0434\u043e\u0440\u043e\u0436\u043d\u043e\u0439 \u0437\u043d\u0430\u043a\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='roadsing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Roadsing_category', verbose_name='\u0420\u0430\u0437\u0434\u0435\u043b'),
        ),
    ]
