# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20170728_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='title',
            field=models.CharField(max_length=600, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
