# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20170807_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsing',
            name='img2',
            field=models.ImageField(blank=True, upload_to='roadsing', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='roadsing',
            name='img3',
            field=models.ImageField(blank=True, upload_to='roadsing', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='roadsing',
            name='img4',
            field=models.ImageField(blank=True, upload_to='roadsing', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='roadsing',
            name='img5',
            field=models.ImageField(blank=True, upload_to='roadsing', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='roadsing',
            name='img6',
            field=models.ImageField(blank=True, upload_to='roadsing', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
