# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20170830_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('body', tinymce.models.HTMLField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0433\u0443\u043b\u0438\u0440\u043e\u0432\u0449\u0438\u043a',
                'verbose_name_plural': '         \u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0420\u0435\u0433\u0443\u043b\u0438\u0440\u043e\u0432\u0449\u0438\u043a\u0430',
            },
        ),
    ]
