# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-30 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20170904_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsing',
            name='number',
            field=models.CharField(max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440'),
        ),
    ]
