# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footerpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u043f\u043e\u0434\u0432\u0430\u043b\u0430', 'verbose_name_plural': '                 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u043f\u043e\u0434\u0432\u0430\u043b\u0430'},
        ),
    ]
