# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0041_auto_20170420_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='\u041a\u043b\u044e\u0447\u0438', max_length=300)),
                ('description', models.CharField(default='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435', max_length=300)),
                ('fio', models.CharField(max_length=300, verbose_name='\u0424.\u0418.\u041e.')),
                ('age', models.SmallIntegerField(verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442')),
                ('zodiac', models.CharField(max_length=200, verbose_name='\u0417\u043d\u0430\u043a \u0437\u043e\u0434\u0438\u0430\u043a\u0430')),
                ('experience', models.SmallIntegerField(verbose_name='\u0421\u0442\u0430\u0436 \u0432\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('coast', models.SmallIntegerField(verbose_name='\u0426\u0435\u043d\u0430 \u0447\u0430\u0441\u0430 \u0432\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('car', models.CharField(max_length=200, verbose_name='\u041c\u0430\u0440\u043a\u0430 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f')),
                ('credo', models.CharField(max_length=300, verbose_name='\u0416\u0438\u0437\u043d\u0435\u043d\u043d\u043e\u0435 \u043a\u0440\u0435\u0434\u043e')),
                ('hobby', models.CharField(max_length=300, verbose_name='\u0425\u043e\u0431\u0431\u0438')),
                ('about_you', models.TextField(verbose_name='\u0420\u0430\u0441\u0441\u043a\u0430\u0436\u0438\u0442\u0435 \u043e \u0441\u0435\u0431\u0435')),
                ('about_teach', models.TextField(verbose_name='\u0420\u0430\u0441\u0441\u043a\u0430\u0436\u0438\u0442\u0435 \u043e \u0441\u0438\u0441\u0442\u0435\u043c\u0435 \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='\u041b\u043e\u0433\u043e')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('category_education', models.ManyToManyField(blank=True, to='school.Category_education', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.City', verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446')),
            ],
            options={
                'verbose_name': '\u0418\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440',
                'verbose_name_plural': '\u0418\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Teachcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0410\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044c \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0410\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044c \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f',
            },
        ),
    ]
