# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_instructor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
