# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0003_auto_20170420_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u0418\u043c\u044f')),
                ('born', models.DateField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('rating', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5')),
                ('body', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.Instructor', verbose_name='\u0418\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0437\u044b\u0432\u044b \u0418\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440\u043e\u0432',
            },
        ),
    ]
