# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_reviewinstructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinstructor',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
    ]
