# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0008_auto_20170420_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinstructor',
            name='rating',
            field=models.IntegerField(choices=[('A', '1'), ('B', '2'), ('C', '3'), ('D', '4'), ('E', '5')], verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
    ]
