# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0012_instructor_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='film',
            field=models.CharField(max_length=300, verbose_name='\u041b\u044e\u0431\u0438\u043c\u044b\u0439 \u0444\u0438\u043b\u044c\u043c'),
        ),
    ]
