# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0013_auto_20170420_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachcar',
        ),
        migrations.AddField(
            model_name='instructor',
            name='teachcar',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0432\u043e\u044f \u043c\u0430\u0448\u0438\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='car',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u041c\u0430\u0440\u043a\u0430 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f'),
        ),
    ]
