# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0014_auto_20170422_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='teachcar',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0432\u043e\u0439 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044c'),
        ),
    ]
