# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0015_auto_20170427_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='car',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='teachcar',
        ),
        migrations.AddField(
            model_name='instructor',
            name='car_akpp',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u041c\u0430\u0440\u043a\u0430 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f \u0410\u041a\u041f\u041f'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='car_mkpp',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u041c\u0430\u0440\u043a\u0430 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f \u041c\u041a\u041f\u041f'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='smoke',
            field=models.BooleanField(default=False, verbose_name='\u041a\u0443\u0440\u0435\u043d\u0438\u0435'),
        ),
    ]
