# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0016_auto_20170427_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='premium',
            field=models.BooleanField(default='False', verbose_name='\u041f\u0440\u0435\u043c\u0438\u0443\u043c \u0430\u043a\u043a\u0430\u0443\u043d\u0442'),
        ),
    ]
