# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0017_instructor_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='car_learner',
            field=models.BooleanField(default=False, verbose_name='\u0417\u0430\u043d\u044f\u0442\u0438\u044f \u043d\u0430 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u0435 \u0443\u0447\u0435\u043d\u0438\u043a\u0430'),
        ),
    ]
