# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0018_instructor_car_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='city',
            field=models.CharField(max_length=300, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
