# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0019_auto_20170430_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='metro',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u041c\u0435\u0442\u0440\u043e'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='car_akpp',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u041f\u0435\u0440\u0432\u044b\u0439 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='car_mkpp',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u0412\u0442\u043e\u0440\u043e\u0439 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044c'),
        ),
    ]
