# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0021_auto_20170528_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo', verbose_name='\u041b\u043e\u0433\u043e'),
        ),
    ]
