# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0023_remove_reviewinstructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinstructor',
            name='email',
            field=models.EmailField(default='test@ya.ru', max_length=254),
        ),
        migrations.AddField(
            model_name='reviewinstructor',
            name='verificated',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d'),
        ),
    ]
