# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0027_reviewresponceinstructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackinstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u0418\u043c\u044f')),
                ('phone', models.CharField(max_length=12, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.Instructor', verbose_name='\u0418\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430',
                'verbose_name_plural': '                \u0417\u0430\u044f\u0432\u043a\u0438 \u0438\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440\u043e\u0432',
            },
        ),
    ]
