# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-06 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0028_feedbackinstructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='test@yandex.ru', max_length=254),
        ),
    ]
