# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0029_instructor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackinstructor',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
