# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0030_feedbackinstructor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackinstructor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
