# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0031_auto_20171111_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackinstructor',
            options={'ordering': ['-created_at'], 'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430', 'verbose_name_plural': '                \u0417\u0430\u044f\u0432\u043a\u0438 \u0438\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440\u043e\u0432'},
        ),
    ]
