# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_town_in_menu'),
        ('instructors', '0032_auto_20180105_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_town',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='city.Town', verbose_name='\u0413\u043e\u0440\u043e\u0434 \u0438\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440\u0430'),
        ),
    ]
